//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public string Plataforma { get; set; }
        public string Comprador { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioEnvio { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<decimal> IngresoNeto { get; set; }
        public string Nserie { get; set; }
        public string Estado { get; set; }
        public string Observación { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
